# Generated by Django 3.1.5 on 2021-03-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002_post_domestic_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_Domestic',
        ),
    ]
