# Generated by Django 3.1.5 on 2021-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('F', '해외주식'), ('D', '국내주식')], default='F', max_length=1, verbose_name='CHOICE'),
        ),
    ]
