# Generated by Django 3.1.5 on 2021-02-26 14:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainphoto',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
