# Generated by Django 3.1.5 on 2021-03-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='blogpost_connected',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='text',
            new_name='content',
        ),
    ]
