# Generated by Django 3.1.5 on 2021-03-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210303_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='n_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
