# Generated by Django 3.1.6 on 2021-03-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_n_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='n_hit',
        ),
    ]
