# Generated by Django 3.1.5 on 2021-02-27 04:29

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210227_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(verbose_name='CONTENT'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='simple description text.', max_length=100, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
        ),
    ]
