# Generated by Django 3.1.6 on 2021-02-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210227_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
